### ISSUE TITLE
Où est passé le code source ?

### ISSUE THREAD

**Issue by aairom** [philippart-s/programmez-josdk-article#1]
Où est passé le code source ?

**Comment by philippart-s** [comment]
il était encore dans une branche, je l'ai mergé sur la branche principale.
merci de la vigilance ;)

**Comment by aairom** [comment]
Merci de votre réactivité. J'ai vu un post d'Aurélie Vaché au sujet du n° de programmez et j'ai acheté par curiosité ! Pour info un projet sur lequel j'ai travaillé avec mes collègues il y a quelques temps... https://github.com/IBM/operator-sample-go.
Au plaisir...
